name: build

on:
  workflow_dispatch:


jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: elasticsearch-arm/
          files: elasticsearch-arm/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: wrhsd/elasticsearch-2.4
